name: Auto Update Playlist

on:
  schedule:
    - cron: '0 2 * * *'  # 每天北京时间 10 点（UTC+8）
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install Requests
      run: pip install requests

    - name: Update Playlist
      run: python update.py

    - name: Commit and Push
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add playlist.m3u
        git commit -m "Auto update playlist" || echo "No changes"
        git push
